method: grid
metric:
  name: val_acc
  goal: maximize

parameters:
  MODEL_NAME:
    values: ["ResNet50"]
  BATCH_SIZE:
    values: [32]
  LEARNING_RATE:
    values: [0.00001]
  NUM_EPOCHS:
    values: [20]
  USE_TRANSFORM_AUGMENTATION_IN_TRAINING:
    values: [False]
  USE_CLAHE:
    values: [False]
  USE_OSTEOPENIA:
    values: [True]
  USE_METABOLIC_FOR_TEST:
    values: [True]
  USE_LABEL_SMOOTHING:
    values: [True]
  LABEL_SMOOTHING_EPSILON:
    values: [0.1]
  USE_CONFIDENCE_WEIGHTED_LOSS:
    values: [True]
  USE_HARD_SAMPLING:
    values: [True]
  CONFIDENCE_THRESHOLD:
    values: [0.8]
  CONFIDENCE_PENALTY_WEIGHT:
    values: [3.0]
  NUM_WORKERS:
    values: [1]
  DATA_DIR:
    values: ["data/new_data/concat_when_both/train"]
  TEST_DATA_DIR:
    values: ["data/new_data/concat_when_both/test"]
