method: grid
metric:
  name: val_acc
  goal: maximize
parameters:
  LEARNING_RATE:
    values: [0.000001]
  BATCH_SIZE:
    values: [32]
  NUM_WORKERS:
    value: 1
  NUM_EPOCHS:
    value: 30
  USE_OSTEOPENIA:
    values: [True]
  MODEL_NAME:
    values: ["DINOv2", "ResNet50"]