method: grid
metric:
  name: val_acc
  goal: maximize
parameters:
  LEARNING_RATE:
    values: [0.00001,0.000001]
  BATCH_SIZE:
    values: [32,64,128]
  NUM_WORKERS:
    value: 1
  NUM_EPOCHS:
    value: 20
  USE_OSTEOPENIA:
    values: [True, False]
  MODEL_NAME:
    values: ["ViT"]
  USE_CLAHE:
    values: [True, False]
  DATA_DIR:
    values: ["data/cropped_data"]
  USE_METABOLIC_FOR_TEST:
    values: [True]
  MERGE_RESULTS_TO_METABOLIC_DF:
    values: [True]
  EXCEL_PATH:
    values: ["data/test_cropped_data/patient_details.xlsx"]