method: grid
metric:
  name: val_acc
  goal: maximize

parameters:
  MODEL_NAME:
    values: ["ResNet50"]
  BATCH_SIZE:
    values: [32]
  LEARNING_RATE:
    values: [0.0001]
  FINE_TUNE_LR_MULTIPLIER: 
    values: [1.0]
  NUM_EPOCHS:
    values: [2]
  USE_TRANSFORM_AUGMENTATION_IN_TRAINING:
    values: [False]
  USE_CLAHE:
    values: [False]
  USE_OSTEOPENIA:
    values: [True]
  USE_METABOLIC_FOR_TEST:
    values: [False]
  USE_LABEL_SMOOTHING:
    values: [True]
  LABEL_SMOOTHING_EPSILON:
    values: [0.2]
  USE_CONFIDENCE_WEIGHTED_LOSS:
    values: [True]
  USE_HARD_SAMPLING:
    values: [True]
  CONFIDENCE_THRESHOLD:
    values: [0.75]
  CONFIDENCE_PENALTY_WEIGHT:
    values: [2.0]
  NUM_WORKERS:
    values: [1]
  DATA_DIR:
    values: ["data/step_6_cropped_only_both"]
  TEST_DATA_DIR:
    values: ["data/new_data/concat_when_both/test"]

