method: grid
metric:
  name: val_acc
  goal: maximize
parameters:
  LEARNING_RATE:
    values: [0.000001]
  BATCH_SIZE:
    values: [64]
  NUM_WORKERS:
    value: 1
  NUM_EPOCHS:
    value: 1
  USE_OSTEOPENIA:
    values: [True]
  MODEL_NAME:
    values: ["ViT"]
  USE_CLAHE:
    values: [True]
  DATA_DIR:
    values: ["data/cropped_data"]
  USE_METABOLIC_FOR_TEST:
    values: [True]
  MERGE_RESULTS_TO_METABOLIC_DF:
    values: [True]  