method: grid
metric:
  name: val_acc
  goal: maximize
parameters:
  LEARNING_RATE:
    values: [0.00001]
  BATCH_SIZE:
    values: [4,16,32,64]
  NUM_WORKERS:
    value: 1
  NUM_EPOCHS:
    value: 20
  USE_OSTEOPENIA:
    values: [True, False]
  MODEL_NAME:
    values: ["ResNet50"]
  USE_CLAHE:
    values: [True, False]
  DATA_DIR:
    values: ["data/cropped_data"]
  USE_METABOLIC_FOR_TEST:
    values: [True]
  MERGE_RESULTS_TO_METABOLIC_DF:
    values: [True]  