method: grid
metric:
  name: val_acc
  goal: maximize

parameters:
  MODEL_NAME:
    values: ["resnet34"]
  BATCH_SIZE:
    values: [32]
  LEARNING_RATE:
    values: [0.0001]
  FINE_TUNE_LR_MULTIPLIER: 
    values: [0.1]
  NUM_EPOCHS:
    values: [3]
  USE_TRANSFORM_AUGMENTATION_IN_TRAINING:
    values: [True]
  USE_CLAHE:
    values: [False]
  USE_OSTEOPENIA:
    values: [True]
  USE_TEST_DATA_DIR:
    values: [True]
  USE_LABEL_SMOOTHING:
    values: [True]
  LABEL_SMOOTHING_EPSILON:
    values: [0.1]
  USE_CONFIDENCE_WEIGHTED_LOSS:
    values: [False]
  USE_HARD_SAMPLING:
    values: [False]
  CONFIDENCE_THRESHOLD:
    values: [0.85]
  CONFIDENCE_PENALTY_WEIGHT:
    values: [2.0]
  NUM_WORKERS:
    values: [1]
  DATA_DIR:
    values: ["/content/osteoporosis_project/data/grand_finalle_data/no_yolo/train_data"]
  TEST_DATA_DIR:
    values: ["/content/osteoporosis_project/data/grand_finalle_data/no_yolo/test_data"]
  RESNET_LAYERS_TO_TRAIN:
    values: [["fc","layer2","layer3","layer4"]]
  DROPOUT:
    values: [0.5]
  USE_SCHEDULER: 
    values: [False]
